name: Build and Release

on: push

jobs:
  createrelease:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.sha }}
        name: Release ${GITHUB_SHA:0:7}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build packages
    needs: createrelease
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            CMD_BUILD: |
                pyinstaller --onefile main.py &&
                cd dist/ &&
                zip -r9 SimpleBuckshotRouletteHelper-macos.zip SimpleBuckshotRouletteHelper.app/
            OUT_FILE_NAME: SimpleBuckshotRouletteHelper-macos.zip
            ASSET_MIME: application/zip
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: pyinstaller --onefile main.py
            OUT_FILE_NAME: SimpleBuckshotRouletteHelper-windows.exe
            ASSET_MIME: application/vnd.microsoft.portable-executable
          - os: ubuntu-latest
            TARGET: linux
            CMD_BUILD: pyinstaller --onefile main.py
            OUT_FILE_NAME: SimpleBuckshotRouletteHelper-linux
            ASSET_MIME: application/octet-stream
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build with PyInstaller for ${{ matrix.TARGET }}
      run: ${{ matrix.CMD_BUILD }}

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/${{ matrix.OUT_FILE_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
