name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read

jobs:
  build:
    name: Build Executables
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      
      - name: Build executable
        run: pyinstaller --onefile main.py
      
      - name: Rename executable
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            mv dist/main.exe dist/SimpleBuckshotRouletteCounter-${{ github.sha }}.exe
          else
            mv dist/main dist/SimpleBuckshotRouletteCounter-${{ github.sha }}
          fi
        shell: bash
      
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-executable
          path: dist/*

  create-release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.run_number }}-${{ github.sha }}
          release_name: Release ${{ github.run_number }}-${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Release Asset (Windows)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/SimpleBuckshotRouletteCounter-${{ github.sha }}.exe
          asset_name: SimpleBuckshotRouletteCounter-${{ github.sha }}.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Asset (Linux)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/SimpleBuckshotRouletteCounter-${{ github.sha }}
          asset_name: SimpleBuckshotRouletteCounter-${{ github.sha }}
          asset_content_type: application/octet-stream
